# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               "Phila.gov Patterns"
url:                 http://cityofphiladelphia.github.io/patterns
baseurl:             /patterns
destination:        _site
description:        The official Pattern Portfolio for phila.gov
version:            1.0.0
exclude:            [
                      'package.json',
                      'Gruntfile.js',
                      'js/src',
                      '_scss'
                    ]

collections:
  patterns:
    output: true
  templates:
    output: true
