# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               "Phila.gov Patterns"
url:                 http://cityofphiladelphia.github.io/patterns
baseurl:             /patterns
destination:        _site
description:        The official Pattern Portfolio for phila.gov
version:            0.7.0
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

collections:
  patterns:
    output: true
  templates:
    output: true
